crds:
  upgradeJob:
    nodeSelector:
      node-role: "observ"

alertmanager:  
  alertmanagerSpec:
    nodeSelector:
      node-role: "observ"

prometheusOperator:
  admissionWebhooks:
    deployment:
      nodeSelector:
        node-role: "observ"
    patch:
      nodeSelector:
        node-role: "observ"
  nodeSelector:
    node-role: "observ"

prometheus:
  prometheusSpec:
    nodeSelector:
      node-role: "observ"

grafana:
  nodeSelector:
    node-role: "observ"
  service:
    type: NodePort
    selector:
      app.kubernetes.io/instance: prometheus-stack
      app.kubernetes.io/name: grafana
    port: 81
    targetPort: 3000
    nodePort: 30081
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Loki
        type: loki
        url: http://loki-gateway.observ.svc.cluster.local/
        access: proxy
        isDefault: false

kube-state-metrics:
  nodeSelector:
    node-role: "observ"

thanosRuler:  
  thanosRulerSpec:
    nodeSelector:
      node-role: "observ"