config:
  clients:
    - url: http://loki-gateway.observ.svc.cluster.local/loki/api/v1/push
      tenant_id: 1
  scrapeConfigs:
    - job_name: kubernetes-pods
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
        - source_labels: [__meta_kubernetes_pod_container_name]
          target_label: container
tolerations:
  - key: "node-role"        
    operator: "Equal"
    value: "observ"        
    effect: "NoSchedule"