apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: google-online-boutique
  namespace: cicd
spec:
  project: otus-mvp-project
  source:
    repoURL: https://github.com/Kuber-2024-10OTUS/Valyanchik_repo.git
    targetRevision: kubernetes-mvp   ##ветка, в которой лежит чарт по пути в path
    path: kubernetes-mvp/04-app/helm-chart/
    helm:
      releaseName: google-online-boutique
      valueFiles:
        - ./values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true