global:
  nodeSelector:
    node-role: "cicd"
  tolerations:
  - key: "node-role"
    operator: "Equal"
    value: "cicd"
    effect: "NoSchedule"
server:  
  service:
    nodePortHttp: 30082
    type: NodePort
    selector:
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/name: rgocd-server
    ports:
      - name: http
        protocol: TCP
        port: 80
        targetPort: 8080
        nodePort: 30082